//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitResources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the street address of your contact..
        /// </summary>
        internal static string HelpAddress {
            get {
                return ResourceManager.GetString("HelpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the city of residence for your contact..
        /// </summary>
        internal static string HelpCity {
            get {
                return ResourceManager.GetString("HelpCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the full name of your contact..
        /// </summary>
        internal static string HelpName {
            get {
                return ResourceManager.GetString("HelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a phone number for your contact..
        /// </summary>
        internal static string HelpPhone {
            get {
                return ResourceManager.GetString("HelpPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the state of residence.
        /// </summary>
        internal static string HelpState {
            get {
                return ResourceManager.GetString("HelpState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the postal code for your contact..
        /// </summary>
        internal static string HelpZip {
            get {
                return ResourceManager.GetString("HelpZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string strAddress {
            get {
                return ResourceManager.GetString("strAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string strCity {
            get {
                return ResourceManager.GetString("strCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string strPhone {
            get {
                return ResourceManager.GetString("strPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string strState {
            get {
                return ResourceManager.GetString("strState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track all your contacts in one convenient location..
        /// </summary>
        internal static string strSubTitle {
            get {
                return ResourceManager.GetString("strSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Galore!.
        /// </summary>
        internal static string strTitle {
            get {
                return ResourceManager.GetString("strTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code:.
        /// </summary>
        internal static string strZip {
            get {
                return ResourceManager.GetString("strZip", resourceCulture);
            }
        }
    }
}
